// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"wczero/services/wallpaper/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/wallpaper/import",
				Handler: ImportHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Error},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/wallpaper/remove",
					Handler: RemoveHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/wallpaper/detail",
					Handler: DetailHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
