// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mp.proto

package mp

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MPTextMsgRequest struct {
	ToUserName           string   `protobuf:"bytes,1,opt,name=ToUserName,proto3" json:"ToUserName,omitempty"`
	FromUserName         string   `protobuf:"bytes,2,opt,name=FromUserName,proto3" json:"FromUserName,omitempty"`
	CreateTime           int64    `protobuf:"varint,3,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	MsgType              string   `protobuf:"bytes,4,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	MsgId                int64    `protobuf:"varint,6,opt,name=MsgId,proto3" json:"MsgId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MPTextMsgRequest) Reset()         { *m = MPTextMsgRequest{} }
func (m *MPTextMsgRequest) String() string { return proto.CompactTextString(m) }
func (*MPTextMsgRequest) ProtoMessage()    {}
func (*MPTextMsgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc352e06cd42aee9, []int{0}
}

func (m *MPTextMsgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MPTextMsgRequest.Unmarshal(m, b)
}
func (m *MPTextMsgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MPTextMsgRequest.Marshal(b, m, deterministic)
}
func (m *MPTextMsgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MPTextMsgRequest.Merge(m, src)
}
func (m *MPTextMsgRequest) XXX_Size() int {
	return xxx_messageInfo_MPTextMsgRequest.Size(m)
}
func (m *MPTextMsgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MPTextMsgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MPTextMsgRequest proto.InternalMessageInfo

func (m *MPTextMsgRequest) GetToUserName() string {
	if m != nil {
		return m.ToUserName
	}
	return ""
}

func (m *MPTextMsgRequest) GetFromUserName() string {
	if m != nil {
		return m.FromUserName
	}
	return ""
}

func (m *MPTextMsgRequest) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *MPTextMsgRequest) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *MPTextMsgRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MPTextMsgRequest) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

type MPTextMsgResponse struct {
	ToUserName           string   `protobuf:"bytes,1,opt,name=ToUserName,proto3" json:"ToUserName,omitempty"`
	FromUserName         string   `protobuf:"bytes,2,opt,name=FromUserName,proto3" json:"FromUserName,omitempty"`
	CreateTime           int64    `protobuf:"varint,3,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	MsgType              string   `protobuf:"bytes,4,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MPTextMsgResponse) Reset()         { *m = MPTextMsgResponse{} }
func (m *MPTextMsgResponse) String() string { return proto.CompactTextString(m) }
func (*MPTextMsgResponse) ProtoMessage()    {}
func (*MPTextMsgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc352e06cd42aee9, []int{1}
}

func (m *MPTextMsgResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MPTextMsgResponse.Unmarshal(m, b)
}
func (m *MPTextMsgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MPTextMsgResponse.Marshal(b, m, deterministic)
}
func (m *MPTextMsgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MPTextMsgResponse.Merge(m, src)
}
func (m *MPTextMsgResponse) XXX_Size() int {
	return xxx_messageInfo_MPTextMsgResponse.Size(m)
}
func (m *MPTextMsgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MPTextMsgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MPTextMsgResponse proto.InternalMessageInfo

func (m *MPTextMsgResponse) GetToUserName() string {
	if m != nil {
		return m.ToUserName
	}
	return ""
}

func (m *MPTextMsgResponse) GetFromUserName() string {
	if m != nil {
		return m.FromUserName
	}
	return ""
}

func (m *MPTextMsgResponse) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *MPTextMsgResponse) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *MPTextMsgResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*MPTextMsgRequest)(nil), "mp.MPTextMsgRequest")
	proto.RegisterType((*MPTextMsgResponse)(nil), "mp.MPTextMsgResponse")
}

func init() { proto.RegisterFile("mp.proto", fileDescriptor_fc352e06cd42aee9) }

var fileDescriptor_fc352e06cd42aee9 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc8, 0x2d, 0xd0, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xca, 0x2d, 0x50, 0x3a, 0xc0, 0xc8, 0x25, 0xe0, 0x1b, 0x10,
	0x92, 0x5a, 0x51, 0xe2, 0x5b, 0x9c, 0x1e, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xc7,
	0xc5, 0x15, 0x92, 0x1f, 0x5a, 0x9c, 0x5a, 0xe4, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8,
	0xc1, 0x19, 0x84, 0x24, 0x22, 0xa4, 0xc4, 0xc5, 0xe3, 0x56, 0x94, 0x9f, 0x0b, 0x57, 0xc1, 0x04,
	0x56, 0x81, 0x22, 0x06, 0x32, 0xc3, 0xb9, 0x28, 0x35, 0xb1, 0x24, 0x35, 0x24, 0x33, 0x37, 0x55,
	0x82, 0x59, 0x81, 0x51, 0x83, 0x39, 0x08, 0x49, 0x44, 0x48, 0x82, 0x8b, 0xdd, 0xb7, 0x38, 0x3d,
	0xa4, 0xb2, 0x20, 0x55, 0x82, 0x05, 0xac, 0x1d, 0xc6, 0x05, 0xc9, 0x38, 0xe7, 0xe7, 0x95, 0xa4,
	0xe6, 0x95, 0x48, 0xb0, 0x42, 0x64, 0xa0, 0x5c, 0x21, 0x11, 0x2e, 0x56, 0xdf, 0xe2, 0x74, 0xcf,
	0x14, 0x09, 0x36, 0xb0, 0x71, 0x10, 0x8e, 0xd2, 0x6a, 0x46, 0x2e, 0x41, 0x24, 0x2f, 0x14, 0x17,
	0xe4, 0xe7, 0x15, 0xa7, 0x0e, 0x56, 0x3f, 0x18, 0xd9, 0x71, 0x31, 0xf9, 0x06, 0x08, 0x59, 0x70,
	0x71, 0xc2, 0x9d, 0x2c, 0x24, 0xa2, 0x97, 0x5b, 0xa0, 0x87, 0x1e, 0x09, 0x52, 0xa2, 0x68, 0xa2,
	0x10, 0x7f, 0x25, 0xb1, 0x81, 0xe3, 0xce, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xca, 0x9c, 0x91,
	0x1f, 0xc7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MPClient is the client API for MP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MPClient interface {
	MPTextMsg(ctx context.Context, in *MPTextMsgRequest, opts ...grpc.CallOption) (*MPTextMsgResponse, error)
}

type mPClient struct {
	cc *grpc.ClientConn
}

func NewMPClient(cc *grpc.ClientConn) MPClient {
	return &mPClient{cc}
}

func (c *mPClient) MPTextMsg(ctx context.Context, in *MPTextMsgRequest, opts ...grpc.CallOption) (*MPTextMsgResponse, error) {
	out := new(MPTextMsgResponse)
	err := c.cc.Invoke(ctx, "/mp.MP/MPTextMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MPServer is the server API for MP service.
type MPServer interface {
	MPTextMsg(context.Context, *MPTextMsgRequest) (*MPTextMsgResponse, error)
}

// UnimplementedMPServer can be embedded to have forward compatible implementations.
type UnimplementedMPServer struct {
}

func (*UnimplementedMPServer) MPTextMsg(ctx context.Context, req *MPTextMsgRequest) (*MPTextMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MPTextMsg not implemented")
}

func RegisterMPServer(s *grpc.Server, srv MPServer) {
	s.RegisterService(&_MP_serviceDesc, srv)
}

func _MP_MPTextMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MPTextMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPServer).MPTextMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mp.MP/MPTextMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPServer).MPTextMsg(ctx, req.(*MPTextMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MP_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mp.MP",
	HandlerType: (*MPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MPTextMsg",
			Handler:    _MP_MPTextMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mp.proto",
}
