// Code generated by goctl. DO NOT EDIT!
// Source: wallpaper.proto

package server

import (
	"context"

	"wczero/services/wallpaper/rpc/internal/logic"
	"wczero/services/wallpaper/rpc/internal/svc"
	"wczero/services/wallpaper/rpc/wallpaper"
)

type WallpaperServer struct {
	svcCtx *svc.ServiceContext
	wallpaper.UnimplementedWallpaperServer
}

func NewWallpaperServer(svcCtx *svc.ServiceContext) *WallpaperServer {
	return &WallpaperServer{
		svcCtx: svcCtx,
	}
}

func (s *WallpaperServer) Import(ctx context.Context, in *wallpaper.ImportRequest) (*wallpaper.ImportResponse, error) {
	l := logic.NewImportLogic(ctx, s.svcCtx)
	return l.Import(in)
}

func (s *WallpaperServer) Remove(ctx context.Context, in *wallpaper.RemoveRequest) (*wallpaper.RemoveResponse, error) {
	l := logic.NewRemoveLogic(ctx, s.svcCtx)
	return l.Remove(in)
}

func (s *WallpaperServer) Detail(ctx context.Context, in *wallpaper.DetailRequest) (*wallpaper.DetailResponse, error) {
	l := logic.NewDetailLogic(ctx, s.svcCtx)
	return l.Detail(in)
}

func (s *WallpaperServer) List(ctx context.Context, in *wallpaper.ListRequest) (*wallpaper.ListResponse, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

func (s *WallpaperServer) Category(ctx context.Context, in *wallpaper.CategoryRequest) (*wallpaper.CategoryResponse, error) {
	l := logic.NewCategoryLogic(ctx, s.svcCtx)
	return l.Category(in)
}
