// Code generated by goctl. DO NOT EDIT!
// Source: mp.proto

package mpclient

import (
	"context"

	"wczero/services/mp/rpc/mp"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = mp.Request
	Response = mp.Response

	MP interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultMP struct {
		cli zrpc.Client
	}
)

func NewMP(cli zrpc.Client) MP {
	return &defaultMP{
		cli: cli,
	}
}

func (m *defaultMP) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := mp.NewMPClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
