// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"wczero/services/user/rpc/internal/logic"
	"wczero/services/user/rpc/internal/svc"
	"wczero/services/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) WeChatLogin(ctx context.Context, in *user.WeChatLoginRequest) (*user.WeChatLoginResponse, error) {
	l := logic.NewWeChatLoginLogic(ctx, s.svcCtx)
	return l.WeChatLogin(in)
}
