// Code generated by goctl. DO NOT EDIT!
// Source: mp.proto

package server

import (
	"context"

	"wczero/services/mp/rpc/internal/logic"
	"wczero/services/mp/rpc/internal/svc"
	"wczero/services/mp/rpc/mp"
)

type MPServer struct {
	svcCtx *svc.ServiceContext
	mp.UnimplementedMPServer
}

func NewMPServer(svcCtx *svc.ServiceContext) *MPServer {
	return &MPServer{
		svcCtx: svcCtx,
	}
}

func (s *MPServer) MPTextMsg(ctx context.Context, in *mp.MPTextMsgRequest) (*mp.MPTextMsgResponse, error) {
	l := logic.NewMPTextMsgLogic(ctx, s.svcCtx)
	return l.MPTextMsg(in)
}
