// Code generated by goctl. DO NOT EDIT.
package types

type WeChatLoginRequest struct {
	AppID string `json:"appid"`
	Code  string `json:"code"`
}

type WeChatLoginResponse struct {
	Token string `json:"token"`
}
