// Code generated by goctl. DO NOT EDIT.
package types

type WallPaperInfo struct {
	Wid      string `json:"wid"`
	Name     string `json:"name"`
	ImageURL string `json:"image_url"`
	Author   string `json:"author"`
	Desc     string `json:"desc"`
}

type ImportRequest struct {
	List []WallPaperInfo `json:"list"`
}

type ImportResponse struct {
}

type RemoveRequest struct {
	List []string `json:"list"`
}

type RemoveResponse struct {
}

type DetailRequest struct {
	Wid   string `form:"wid"` // if id not exists, so query all
	Start int64  `form:"start"`
	Limit int64  `form:"limit"`
}

type DetailResponse struct {
	List  []WallPaperInfo `json:"list"`
	Total int64           `json:"total"`
}
