// Code generated by goctl. DO NOT EDIT.
package types

type MPBasicSetupRequest struct {
	Signature string `form:"signature"`
	Timestamp string `form:"timestamp"`
	Nonce     string `form:"nonce"`
	EchoStr   int64  `form:"echostr"`
}

type MPBasicSetupResponse struct {
	Reply int64 `json:"reply"`
}
